modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/RaphiMC/ImmediatelyFast/issues"
license = "LGPL-3.0"

[[mods]]
modId = "immediatelyfast"
version = "${version}"
displayName = "ImmediatelyFast"
authors = "RK_01"
description = '''
Speed up and optimize immediate mode rendering in Minecraft
'''
logoFile = "assets/immediatelyfast/icon.png"

[[dependencies.immediatelyfast]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.immediatelyfast]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "CLIENT"
